generic:
  replicaCount: 1
  image:
    repository: ealen/echo-server
    tag: 0.9.2@sha256:006b92e1d6682442e29d1d0d73c34a61166d42f8a5bf1ea10c318f07ad4790e2
  container:
    port: 80
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: echo.dixneuf19.fr
        paths:
          - path: /
    tls:
      - hosts:
          - echo.dixneuf19.fr
        secretName: echo-dixneuf19-fr-tls
