helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/vitry-auberge-bot
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:e71f0ec39ecf9b69ce972003a390b7cda70869b50a6be123539f2c13129ca932
    forcestring: true
