helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/vitry-auberge-bot
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:907c14589754235b4c518261fb689bc1b367209e3bc3b9d4afcb593b256e6970
    forcestring: true
