apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-passwords
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-passwords
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: baj-mysql-root-password
    - secretKey: mysql-password
      remoteRef:
        key: baj-mysql-password
