#################################################
# Setup kernel modules
#################################################
---
- hosts: 'brassberry*:proxmox_workers'
  become: true

  tasks:
    - name: Enable kernel modules
      blockinfile:
        path: /etc/modules-load.d/modules.conf
        create: true
        block: |
          overlay
          nf_conntrack
          br_netfilter
      register: kernel_module

    - name: Reboot
      reboot: {}
      when: kernel_module.changed
