navidrome:
  env:
    ND_MUSICFOLDER: /music
    ND_LOGLEVEL: info
    ND_SCANNER_SCHEDULE: "@every 15m"
    ND_PROMETHEUS_ENABLED: "true"

  envFrom:
    - secretRef:
        name: navidrome-secrets

  service:
    main:
      monitor:
        enabled: true

  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: navidrome.dixneuf19.fr
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: navidrome-tls
          hosts:
            - navidrome.dixneuf19.fr

  persistence:
    config:
      enabled: true
      mountPath: /data
      storageClass: nfs-client
      accessMode: ReadWriteMany
      size: 1Mi
    music:
      enabled: true
      mountPath: /music
      existingClaim: soundhoard-music
      readOnly: true
