helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/dank-face-slack-bot
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:4770499f42d6a1a90c0a57693627d19bb82748b5e64ef2289af4bca9afc94653
    forcestring: true
