helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/dank-face-slack-bot
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:14c2efa098017188d596898e9db39d5e570e73592ee853134a7e13774ffbcf04
    forcestring: true
