helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/soundhoard
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:7a821ada22e74bb576d994a3d5e3369baeef4cf4309bc9be1bf59b3a9734a6a7
    forcestring: true
