helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/soundhoard
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:6745719c55af0814a42d26a1717d9d6bfbe9c2ff60b270ef69f7ad1d3cf2fe93
    forcestring: true
