helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/soundhoard
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:db27165f3c89a9e6606a08d6021a27d8c06de80a331987bfe493a86681062bf3
    forcestring: true
