generic:
  replicaCount: 1
  image:
    repository: ghcr.io/dixneuf19/soundhoard
    tag: main@sha256:5c1315a2ff48849f3fd59230686ef69035835c06a600529a2d3bb97751025913
  container:
    noProbes: true
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
      cpu: 100m
  ingress:
    enabled: false
  configmap:
    DOWNLOAD_DIR: /music/SoundHoard
  secrets:
    - name: soundhoard
      key: TELEGRAM_BOT_TOKEN
  volumeMounts:
    - name: music
      mountPath: /music
  volumes:
    - name: music
      persistentVolumeClaim:
        claimName: soundhoard-music
