{
 "title": "Keptn Applications",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values(keptn_deployment_app_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "keptn_app_count_total{keptn_deployment_app_status=\"Succeeded\", keptn_deployment_app_name=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_app_active{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "keptn_app_count_total{keptn_deployment_app_status=\"Failed\", keptn_deployment_app_name=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time between Deployments",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_app_previousversion, keptn_deployment_app_version) (keptn_app_deploymentinterval{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "{{keptn_deployment_app_previousversion}} - {{keptn_deployment_app_version}}"
    }
   ]
  },
  {
   "title": "Average Time between Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion) (keptn_app_deploymentinterval{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keptn_deployment_app_version) (keptn_app_deploymentduration{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "{{keptn_workload_version}}"
    }
   ]
  },
  {
   "title": "Deployments Active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(keptn_app_active{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful promotions",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_promotion_count_total{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "operation": "AppPreDeployTasks",
     "service": "lifecycle-operator",
     "tags": "keptn.deployment.app.name=$Application"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "keptn_deployment_deploymentduration{keptn_deployment_app_name=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Keptn Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_task_active{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_evaluation_active{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_task_count{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_evaluation_count_total{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(le) (keptn_task_duration_bucket{job=\"otel-collector\", le!=\"+Inf\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Evaluation Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(le) (keptn_evaluation_duration_bucket{job=\"otel-collector\", le!=\"+Inf\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_deployment_active{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Deployments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_deployment_count{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(le) (keptn_deployment_duration_bucket{job=\"otel-collector\", le!=\"+Inf\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Keptn Workloads",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Workload",
    "query": {
     "query": "label_values(keptn_deployment_workload_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(keptn_deployment_count{keptn_deployment_workload_name=\"$Workload\", keptn_deployment_workload_status=\"Succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time between Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion, keptn_deployment_workload_version) (keptn_deployment_deploymentinterval{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(keptn_deployment_count{keptn_deployment_workload_name=\"$Workload\", keptn_deployment_workload_status=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keptn_deployment_workload_version) (keptn_deployment_deploymentduration{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "{{keptn_workload_version}}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_deployment_active{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time between Deployments",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion, keptn_deployment_workload_version) (keptn_deployment_deploymentinterval{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "{{keptn_deployment_workload_previousversion}} - {{keptn_deployment_workload_version}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "operation": "$Workload/WorkloadPreDeployTasks",
     "service": "lifecycle-operator"
    }
   ]
  },
  {
   "title": "Deployments Active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "max(keptn_deployment_active{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}