helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/whats-on-fip
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:ca8bd6e87d11ec8d6cefcb7e681e1c427aaa7ab0f48c016549e4ec896912a510
    forcestring: true
