helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/whats-on-fip
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:d442b4e1c19b750eba2bd97143122c55ef22a72bd992f6f361f37d2285bf9ef3
    forcestring: true
