helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/whats-on-fip
    forcestring: true
  - name: generic.image.tag
    value: main@sha256:6bd72adf7ac211538df1ee414f0b26d10275be346a0e6a2b5f36ba52ebe8fd50
    forcestring: true
