generic:
  replicaCount: 1
  image:
    repository: ghcr.io/dixneuf19/whats-on-fip
    tag: main
    pullPolicy: Always
  container:
    port: 80
    noProbes: true
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi
      cpu: 100m
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
  configmap:
    USE_POLLING: "true"
    RADIO_FRANCE_API_HOST: "https://openapi.radiofrance.fr/v1/graphql"
  secrets:
    - name: whats-on-fip
      key: BOT_TELEGRAM_TOKEN
    - name: whats-on-fip
      key: RADIO_FRANCE_API_TOKEN
    - name: whats-on-fip
      key: SPOTIPY_CLIENT_ID
    - name: whats-on-fip
      key: SPOTIPY_CLIENT_SECRET
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - whats-on-fip
            topologyKey: kubernetes.io/hostname
