apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: burrito-admin-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: burrito-admin-credentials
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: admin
        password: '{{ "{{ .password }}" }}'
  data:
    - secretKey: password
      remoteRef:
        key: burrito-admin-password
