---
apiVersion: v1
kind: Service
metadata:
  name: qrcode
spec:
  selector:
    app: qrcode
  ports:
  - port: 80
    targetPort: web
    name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qrcode
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  rules:
  - host: qrcode.dixneuf19.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qrcode
            port:
              name: web
  tls:
  - hosts:
    - qrcode.dixneuf19.fr
    secretName: qrcode-dixneuf19-fr-tls
