apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dank-face-slack-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: dank-face-slack-bot
  data:
    - secretKey: SLACK_CLIENT_ID
      remoteRef:
        key: dank-face-slack-client-id
    - secretKey: SLACK_CLIENT_SECRET
      remoteRef:
        key: dank-face-slack-client-secret
    - secretKey: SLACK_SIGNING_SECRET
      remoteRef:
        key: dank-face-slack-signing-secret
