apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grist-secrets
spec:
  refreshInterval: "0"
  target:
    name: grist-secrets
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grist-session-secret
