apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: burrito-repo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: burrito-repo
    template:
      type: credentials.burrito.tf/repository
      engineVersion: v2
      data:
        provider: github
        url: https://github.com/dixneuf19/brassberry-gitops
        githubAppID: '{{ "{{ .appId }}" }}'
        githubAppInstallationID: '{{ "{{ .installationId }}" }}'
        githubAppPrivateKey: '{{ "{{ .privateKey }}" }}'
        webhookSecret: '{{ "{{ .webhookSecret }}" }}'
  data:
    - secretKey: appId
      remoteRef:
        key: burrito-github-app-id
    - secretKey: installationId
      remoteRef:
        key: burrito-github-app-installation-id
    - secretKey: privateKey
      remoteRef:
        key: burrito-github-app-private-key
    - secretKey: webhookSecret
      remoteRef:
        key: burrito-github-webhook-secret
