apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fip-slack-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: fip-slack-bot
  data:
    - secretKey: SLACK_CLIENT_ID
      remoteRef:
        key: fip-slack-client-id
    - secretKey: SLACK_CLIENT_SECRET
      remoteRef:
        key: fip-slack-client-secret
    - secretKey: SLACK_SIGNING_SECRET
      remoteRef:
        key: fip-slack-signing-secret
