# =============================================================================
# Category A: Secrets generated by random_password / random_string
# These are regenerated from scratch if TF state is lost.
# =============================================================================

# --- KaraKeep ---

resource "random_password" "karakeep_nextauth" {
  length  = 48
  special = false
}

resource "random_string" "karakeep_meili_master_key" {
  length  = 48
  special = false
}

resource "scaleway_secret" "karakeep_secrets" {
  name        = "karakeep-secrets"
  path        = "/k8s"
  description = "KaraKeep generated secrets (NEXTAUTH_SECRET, MEILI_MASTER_KEY). OPENAI_API_KEY is in a separate manual secret."
}

resource "scaleway_secret_version" "karakeep_secrets" {
  secret_id = scaleway_secret.karakeep_secrets.id
  data = jsonencode({
    NEXTAUTH_SECRET  = random_password.karakeep_nextauth.result
    MEILI_MASTER_KEY = random_string.karakeep_meili_master_key.result
  })
}

# --- BAJ MySQL ---

resource "random_password" "baj_mysql_root" {
  length  = 32
  special = false
}

resource "random_password" "baj_mysql_password" {
  length  = 32
  special = false
}

resource "scaleway_secret" "baj_mysql_passwords" {
  name        = "baj-mysql-passwords"
  path        = "/k8s"
  description = "BAJ MySQL passwords (Bitnami chart existingSecret)"
}

resource "scaleway_secret_version" "baj_mysql_passwords" {
  secret_id = scaleway_secret.baj_mysql_passwords.id
  data = jsonencode({
    mysql-root-password = random_password.baj_mysql_root.result
    mysql-password      = random_password.baj_mysql_password.result
  })
}
