---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-selfsigned-issuer
  namespace: external-secrets
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - bitwarden-sdk-server
  issuerRef:
    name: bitwarden-selfsigned-issuer
    kind: Issuer
