apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.eu
      identityURL: https://identity.bitwarden.eu
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: 512cf254-9f26-4e35-b1d1-b42300bb3dca
      projectID: 23028f7d-c2dd-4049-a1ef-b42300e91f30
      auth:
        secretRef:
          credentials:
            name: bws-machine-account-token
            namespace: external-secrets
            key: token
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
