apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.1.30"
    path: "/tank/media/immich"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-library
spec:
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 1Ti
  accessModes:
    - ReadWriteMany
