helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/dank-face-bot
    forcestring: true
  - name: generic.image.tag
    value: master@sha256:39070df158a6dbdeb2ff5aa8a3389f5cd6cf816f18dd973e27f4cecae062dfd8
    forcestring: true
