helm:
  parameters:
  - name: generic.image.name
    value: ghcr.io/dixneuf19/dank-face-bot
    forcestring: true
  - name: generic.image.tag
    value: master@sha256:aacf7c7420b2692cbae91b37ecb5c45615bd9a15fcabb4ef4e58446a8ae624dc
    forcestring: true
